//
//  Constants.swift
//  Appie
//
//  Created by Pieter Bikkel on 27/06/2023.
//

import Foundation

struct Constants {
    static let baseUrlPath = "https://appie.nielsgermeraad.nl/api/v1/"
    static let backupImage = "https://static.ah.nl/dam/product/AHI_43545239383734363237?revLabel=3&rendition=800x800_JPG_Q90&fileType=binary"
    
    struct DefaultModels {
        static let bonusProduct = Product(webshopID: 386832, hqID: 844099, title: "Brouwerij 't IJwit Brouwerij 't IJwit", salesUnitSize: "0,33 l", unitPriceDescription: "normale prijs per liter €7.55", images: [ProductImage(width: 708, height: 708, url: "https://static.ah.nl/dam/product/AHI_43545239353535323037?revLabel=4&rendition=LowRes_JPG&fileType=binary")], bonusStartDate: nil, bonusEndDate: nil, discountType: "AH", segmentType: nil, promotionType: "PERPETUAL", bonusMechanism: "KIES & MIX 6 = 5", currentPrice: 2.49, priceBeforeBonus: nil, orderAvailabilityStatus: "IN_ASSORTMENT", mainCategory: "Bier en aperitieven", subCategory: "Wit bier", brand: "Brouwerij 't IJ", shopType: "AH", availableOnline: true, isPreviouslyBought: false, descriptionHighlights: "<p>Ijwit is een geweldige dorstlesser. Licht troebel, goud van kleur, vol met kruidige en citrusachtige tone.</p><p><ul><li>Zacht  en  kruidig</li><li>Populairste witbier van Nederland</li><li>Lekker met citroen</li><li>Perfect voor de borrel</li></ul></p>", propertyIcons: [], nix18: true, isStapelBonus: false, extraDescriptions: [], bonusSegmentID: nil, bonusSegmentDescription: nil, isBonus: true, hasListPrice: false, descriptionFull: "<strong>Kies & Mix, 6=5 op speciaalbier</strong>\n<p>Van fris en lichtzoet tot krachtig en vol, speciaalbier komt in alle soorten en maten. Gelukkig is kiezen nu gemakkelijk, want je combineert al je favorieten met onze 6=5 actie. Alle deelnemende speciaalbieren vind je <a href=\"https://www.ah.nl/shop/speciaalbieractie\">hier</a></p>.\nIjwit is een stevig witbier dat gevaarlijk lekker doordrinkt. Het is licht troebel en mooi goud van kleur met een heerlijke zachte schuimkraag. De smaak is heerlijk fris en de toevoeging van koriander zaad en citroen zorgen voor licht kruidige en citrusachtige tonen. Door de fijne, lichtzoete afdronk is ijwit een geweldige dorstlesser", isOrderable: true, isInfiniteBonus: true, isSample: false, isBonusPrice: false, isSponsored: false, isVirtualBundle: false, productCount: nil, multipleItemPromotion: false, bonusPeriodDescription: nil, virtualBundleItems: nil)
        
        static let normalProduct = Product(webshopID: 232949, hqID: 825909, title: "Grolsch Pilsener krat", salesUnitSize: "24 x 0,3 l", unitPriceDescription: "prijs per liter €2.50", images: [ProductImage(width: 800, height: 800, url: "https://static.ah.nl/dam/product/AHI_43545239383734363237?revLabel=3&rendition=800x800_JPG_Q90&fileType=binary")], bonusStartDate: nil, bonusEndDate: nil, discountType: nil, segmentType: nil, promotionType: nil, bonusMechanism: nil, currentPrice: nil, priceBeforeBonus: 17.98, orderAvailabilityStatus: "IN_ASSORTMENT", mainCategory: "Bier en aperitieven", subCategory: "Pils - krat", brand: "Grolsch", shopType: "AH", availableOnline: true, isPreviouslyBought: false, descriptionHighlights: "<p>Grolsch Premium pilsner is een verfrissend bier met een zachte afdronk. Het bier wordt gebrouwen met twee soorten hop: voor de smaak en het aroma. Dit geeft Grolsch bier haar unieke karakter.</p><p><ul><li>Premium pilsener bier</li><li>Smaak: hoppig, bitter  en  vol</li><li>Bronze medaille bij world beer awards 2022</li><li>Alcoholpercentage: 5,0%</li></ul></p>", propertyIcons: [], nix18: true, isStapelBonus: false, extraDescriptions: [], bonusSegmentID: nil, bonusSegmentDescription: nil, isBonus: false, hasListPrice: nil, descriptionFull: "<p>Grolsch is een merk dat weinig introductie behoeft. Je Kent ons van de beugel, vakmanschap is meesterschap en de vele speciaalbieren. En natuurlijk van onze uitgesproken smaak want we brouwen al meer dan 400 jaar met zorgvuldig geselecteerde ingredienten en twee soorten hop. Hierdoor zijn onze bieren vol van smaak en hebben ze een rijke afdronk. Grolsch wil mensen gelukkig maken. Het staat voor tijd voor elkaar en mensen om je heen. </p>", isOrderable: true, isInfiniteBonus: false, isSample: false, isBonusPrice: nil, isSponsored: false, isVirtualBundle: false, productCount: nil, multipleItemPromotion: nil, bonusPeriodDescription: nil, virtualBundleItems: nil)
        
        static let shoppingCartItem = ShoppingListItem(name: "Hertog Jan Natuurzuiver bier krat", priceBeforeBonus: 18.89, currentPrice: 14.17, webshopID: 2708, amount: 3, images: [ProductImage(width: 800, height: 800, url: "https://static.ah.nl/dam/product/AHI_43545239373536343339?revLabel=3&rendition=800x800_JPG_Q90&fileType=binary")], description: "Ons pilsener is het visitekaartje van Hertog Jan binnen de reeks bieren. Vanzelfsprekend selecteren we alle ingredienten die we voor het brouwen gebruiken met de allergrootste zorg. Alleen de rijkste mout, de mooiste hop en kristalhelder natuurzuiver water uit de eifel zijn goed genoeg voor ons bier. Dankzij deze ingredienten en natuurlijk de kunde van onze Brouwers krijgt het bier die prachtige gouden kleur en vormt het een mooie, volle schuimkraag. Ons pils is een bier om trots op te zijn.", amountPerUser: [AmountPerUser(name: "Pieter", amount: 5)])
        
        static let listResponse = ListResponse(list: [], total: 0.0, totalBeforeBonus: 0.0, bonusAmount: 0.0, totalPerUser: [])
    }
}
